.\" Process this file with
.\" groff -man -Tascii sfinder.1
.\"
.TH SFINDER 1 2014-04-23 GNU STAMP-FINDER
.SH NAME
sfinder \- raw data timestamp search utility
.SH SYNOPSIS
.B sfinder [-h] [-q] [-E
.I epoch
.B ] [-s
.I start_date
.B ] [-e
.I end_date
.B ] [-l] [-p
.I path
.B ]
.SH DESCRIPTION
.B sfinder
searches for timestamps in files using only the binary
data. This program is written in Python and had raw cell
phone forensic images in mind. Any file containing raw
data can be scanned for timestamps but
.I sfinder
is more
accurate if given specific search parameters. This
program will take time because it of the conversion from
binary data to timestamps. It also searches for every
possibility which means it has to test every byte in the
file. Hashing is also performed to ensure data integrity.
.SH OPTIONS
.IP -h
Show the help message and exit.
.IP -q
Quit Mode. Run
.I sfinder
without hashing files to speed up processing.
.IP "-E epoch"
Set the epoch origin date for the filesystem the image or
file was created. Formatting: 'YYYY,MM,DD'
.IP "-s start_date"
The date you want the search to start at. All timestamps
before this date will be disregarded. Can be set down to
seconds but requires at least the YYYY, MM, and DD to be
set. Formatting: 'YYYY,MM,DD,HH,mm,ss'
.IP "-e end_date"
The date you want the search to stop at. All timestamps
after this date will be disregarded. Can be set down to
seconds but requires at least the YYYY, MM, and DD to be
set. Formatting: 'YYYY,MM,DD,HH,mm,ss'
.IP -l
Search for timestimps in 'Little Endian' format 
.I (cd ab)
instead of the normal 'Big Endian' format 
.I (ab cd).
.IP "-p path"
The path to the file or directory you want
.I sfinder
to scan. If it is a directory, all files in the directory
will be processed.
.SH FILES
.I ~/sfinder/
.RS
The directory containing the output of hashes and timestamp
data.
.RE

.I ~/sfinder.log
.RS
Log file of errors and program run information.
.RE

.I /opt/sfinder/
.RS
Directory where the source code is located at.
.SH ENVIRONMENT
The following are the defaults set when running
.I sfinder

.IP -E
Default
.I epoch
is '1970,1,1'
.IP -s
Default
.I start_date
is one(1) week ago from today.
.IP -e
Default
.I end_date
is today's date.
.IP -l
Default is
.I False
and will run as 'Big Endian'.
.IP -p
Default is the currenty directory
.I sfinder
is being run in.
.SH AUTHOR
Jared Everett <jarsever at gmail dot com>